apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  name: sentiment-hpo
  namespace: kubeflow
  annotations:
    katib.kubeflow.org/validating-webhook: "false"
    katib.kubeflow.org/mutating-webhook: "false"
spec:
  algorithm:
    algorithmName: random
  parallelTrialCount: 2
  maxTrialCount: 4
  maxFailedTrialCount: 2
  objective:
    type: maximize
    goal: 0.75
    objectiveMetricName: accuracy
  metricsCollectorSpec:
    source:
      filter:
        metricsFormat:
        - "([\\w|-]+)\\s*=\\s*([+-]?\\d*(\\.\\d+)?([Ee][+-]?\\d+)?)"
      fileSystemPath:
        path: /var/log/katib/metrics.log
        kind: File
    collector:
      kind: File
  parameters:
  - name: learning_rate
    parameterType: double
    feasibleSpace:
      min: "0.0005"
      max: "0.005"
  - name: hidden_dim
    parameterType: categorical
    feasibleSpace:
      list:
      - "128"
      - "256"
  trialTemplate:
    primaryContainerName: training
    trialParameters:
    - name: learningRate
      description: Learning rate
      reference: learning_rate
    - name: hiddenDim
      description: Hidden dimension
      reference: hidden_dim
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          metadata:
            annotations:
              sidecar.istio.io/inject: "false"
          spec:
            containers:
            - name: training
              image: sentiment-analysis:latest
              imagePullPolicy: Never
              command:
              - sh
              - -c
              - |
                python src/training/train.py \
                  --learning-rate ${trialParameters.learningRate} \
                  --hidden-dim ${trialParameters.hiddenDim} \
                  --epochs 2 \
                  --batch-size 64 \
                  --run-name katib-trial | tee /var/log/katib/metrics.log
              volumeMounts:
              - name: katib-metrics
                mountPath: /var/log/katib
            volumes:
            - name: katib-metrics
              emptyDir: {}
            restartPolicy: Never
        backoffLimit: 1
